spring:
  datasource:
    url: jdbc:mysql://babpul-server.mysql.database.azure.com:3306/babpul_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: babpul
    password: 852456dkssud@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: update # 개발 시에는 update, 운영은 validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

